### ISSUE TITLE
Integrate Moov node with Plaid node link account

### ISSUE THREAD

**Issue by PB-PDX** [moovfinancial/moov-node#59]
Hi, I am having trouble testing the linking process for adding a bank account using the Moov node sdk. I am utilizing Plaid node sdk on the backend to get the Plaid linktoken and then I send it to the front-end where PlaidLink returns another token. This token is getting verified on the backend which produces the Plaid processor token. I then take the user's moov accountID and the processor token(plaidToken) and am passing them here, const result = await moov.bankAccounts.link(accountID, plaidToken);
I am getting an error that I need to enter an bankAccount ID. How do I get this to work? Is this a moov sandbox issue? Maybe that is the reason no bankAccount data is transmitted? It seems that moov.js allows a developer to pass in env: 'sandbox' but the node sdk does not. Please let me know how I can further assist to help trouble shoot.

**Comment by PB-PDX** [comment]
I seemed to have side stepped this issue by using const result = await moov.bankAccounts.link(accountID, undefined, plaidToken); Only problem is I am not getting a conflict error of 409.

**Comment by sethlivingston** [comment]
Hi, @PB-PDX. I apologize for the late response. This one slipped through the cracks.

We only support the Plaid integration through our [Moov.js](https://docs.moov.io/moovjs/sources/bank-accounts/plaid-link/). We also recently updated that documentation to make the process more clear.
