### ISSUE TITLE
Dist code was not included in the 1.0.4 release.

### ISSUE THREAD

**Issue by king0120** [moovfinancial/moov-node#65]
Updating this dependency to latest from npm broke our moov related code. Diving into the node_modules it looks like the `dist` directory was not included. Had to roll back to 1.0.3 for the time being.

**Comment by paulMery** [comment]
up 👍 ! 🙏

**Comment by sethlivingston** [comment]
Fixed in the v1.0.5 release. Thank you for your patience, all.
