### ISSUE TITLE
wrong type response Accouts.list()

### ISSUE THREAD

**Issue by paulMery** [moovfinancial/moov-node#69]
https://github.com/moovfinancial/moov-node/blob/d27d18dfd75ab797aaee7e0c730a1e700079cc43/lib/accounts.js#L383

The type should be Account[] as the response is an array

**Comment by paulMery** [comment]
`{Promise<Account[]>}`

**Comment by sethlivingston** [comment]
Released in https://github.com/moovfinancial/moov-node/releases/tag/v1.1.0
